export const FETCHING_START = "FETCHING_START";
export const FETCHING_FINISHED = "FETCHING_FINISHED";
export const FETCHING_ERROR = "FETCHING_ERROR";
export const RECIPE_SELECT_START = "RECIPE_SELECT_START";
export const RECIPE_SELECT_FINISHED = "RECIPE_SELECT_FINISHED";
export const UPLOAD_SAVED_RECIPE = "UPLOAD_SAVED_RECIPE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_ROUTE = "SET_ROUTE";

export const FAVOURITE_START = "FAVOURITE_START";
export const FAVOURITE_FINISH = "FAVOURITE_FINISH";
export const FAVOURITE_SUCCESSFUL = "FAVOURITE_SUCCESSFUL";
export const FAVOURITE_ERROR = "FAVOURITE_ERROR";
